# Generated by Django 4.0.5 on 2022-08-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectAndTasks', '0002_initial'),
        ('taskMgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task_map',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependent_on_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depending_task', to='projectAndTasks.task'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_of_dependent_task', to='projectAndTasks.task'),
        ),
    ]
