# Generated by Django 4.0.5 on 2022-08-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0002_designation_alter_user_job_delete_roles'),
        ('projectAndTasks', '0006_project_category_map'),
        ('taskMgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Task',
            new_name='User_Task_Map',
        ),
    ]
