# Generated by Django 4.0.5 on 2022-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='description',
            field=models.CharField(default='milestone description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='title',
            field=models.CharField(default='milestone title', max_length=255, null=True),
        ),
    ]
