# Generated by Django 4.0.5 on 2022-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task_map',
            name='wage',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_task_map',
            name='weekly_effort',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
