# Generated by Django 4.0.5 on 2022-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMgmt', '0002_rename_user_task_user_task_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task_map',
            name='assign_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
