# Generated by Django 4.0.5 on 2022-08-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0001_initial'),
        ('taskMgmt', '0002_alter_milestones_description_alter_milestones_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectAndTasks.task'),
        ),
    ]
