# Generated by Django 4.0.5 on 2022-08-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMgmt', '0003_alter_user_task_map_assign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task_map',
            name='wage',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_task_map',
            name='weekly_effort',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
