# Generated by Django 4.0.5 on 2022-08-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Project', max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('allocated_time', models.IntegerField(default=None, null=True)),
                ('budget', models.IntegerField(default=1000, null=True)),
                ('dev_type', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Category_Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=200, null=True)),
                ('description', models.CharField(default=None, max_length=600, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateField(default=None, null=True)),
                ('end_time', models.DateField(default=None, null=True)),
                ('slack_time', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('Completed', 'completed'), ('Ongoing', 'ongoing'), ('Postponed', 'postponed'), ('Not Started', 'not started')], default='Not Started', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHierarchy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Project_Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField(default=None, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectAndTasks.project')),
            ],
        ),
    ]
