# Generated by Django 4.0.5 on 2022-08-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0001_initial'),
        ('projectAndTasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='userMgmt.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='userMgmt.user')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectAndTasks.task')),
            ],
        ),
    ]
