# Generated by Django 4.0.5 on 2022-08-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0001_initial'),
        ('projectAndTasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomments',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userMgmt.user'),
        ),
    ]
