# Generated by Django 4.0.5 on 2022-08-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_url', models.URLField(max_length=500)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectAndTasks.task')),
            ],
        ),
    ]
