# Generated by Django 4.0.5 on 2022-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0002_taskcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomments',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
