# Generated by Django 4.0.5 on 2022-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
    ]
