# Generated by Django 4.0.5 on 2022-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0003_taskcomments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
