# Generated by Django 4.0.5 on 2022-08-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0004_alter_taskcomments_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomments',
            old_name='time',
            new_name='comment_time',
        ),
    ]
