# Generated by Django 4.0.5 on 2022-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0004_taskcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'completed'), ('Ongoing', 'ongoing'), ('Postponed', 'postponed'), ('Not Started', 'not started')], default='Not Started', max_length=15),
        ),
    ]
