# Generated by Django 4.0.5 on 2022-08-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costEstimation', '0004_alter_funccategory_allocated_budget_and_more'),
        ('projectAndTasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Category_Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costEstimation.funccategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectAndTasks.project')),
            ],
        ),
    ]
