# Generated by Django 4.0.5 on 2022-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAndTasks', '0006_project_category_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project_map',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
