# Generated by Django 4.0.5 on 2022-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costEstimation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funccategory',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
