# Generated by Django 4.0.5 on 2022-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costEstimation', '0002_funccategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='funccategory',
            name='allocated_budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='funccategory',
            name='expected_time',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='funccategory',
            name='man_hour_per_week',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
