# Generated by Django 4.0.5 on 2022-08-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costEstimation', '0004_alter_funccategory_allocated_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funccategory',
            name='cost_per_loc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='funccategory',
            name='difficulty',
            field=models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='E', max_length=15),
        ),
        migrations.AddField(
            model_name='funccategory',
            name='loc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='funccategory',
            name='loc_per_pm',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
