# Generated by Django 4.0.5 on 2022-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costEstimation', '0005_funccategory_cost_per_loc_funccategory_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funccategory',
            name='estimated_cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
