# Generated by Django 4.0.5 on 2022-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costEstimation', '0006_funccategory_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='funccategory',
            name='misc_cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
