# Generated by Django 4.0.5 on 2022-07-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(default=None, max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('salary_valid_till', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userMgmt.designation'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
